# Generated by Django 3.0.7 on 2020-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20201106_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
